# Generated by Django 4.2.1 on 2023-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='User_profiles/', verbose_name='Profile Image'),
        ),
    ]
