# Generated by Django 4.1.5 on 2023-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, verbose_name='Dish name')),
                ('food_price', models.IntegerField(verbose_name='Dish price')),
                ('final_output_price', models.IntegerField(verbose_name='Dish Output price')),
                ('food_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Foodorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_owner', models.CharField(max_length=255)),
                ('i_d', models.IntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Order item name')),
                ('price', models.IntegerField(verbose_name='Order item price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Order item quantity')),
                ('cart_used', models.ManyToManyField(to='menu.cart')),
            ],
        ),
    ]
