# Generated by Django 4.2.1 on 2023-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Menu_items/', verbose_name='Dish Image'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Order item picture'),
        ),
    ]
