# Generated by Django 4.2.1 on 2023-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_food_picture_foodorder_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
