# Generated by Django 4.1.5 on 2023-05-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_cart_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='order_owner',
        ),
    ]
