# Generated by Django 4.2.1 on 2023-05-29 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_remove_foodorder_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Site_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='order_owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
