# Generated by Django 4.2.1 on 2023-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cart_site_user_foodorder_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium'), ('F', 'Full'), ('H', 'Half')], default='L', max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='final_output_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dish Output price'),
        ),
    ]
