# Generated by Django 4.2.1 on 2023-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_food_serving_size_alter_food_final_output_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Order item name'),
        ),
    ]
